export const GITHUB_CLIENT_ID = '8d970ed03ae6f5d51356';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES';
export const SEARCH_REPOSITORIES_REQUEST = 'SEARCH_REPOSITORIES_REQUEST';
